// Zero-dependency build: bundles modules + images into dist/index.html (deploy) and dist/artifact.html (preview).
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
const u = (p) => new URL(p, import.meta.url);
// Netlify exposes the site URL as process.env.URL; fall back to the placeholder domain locally.
const SITE_URL = (process.env.SITE_URL || process.env.URL || "https://www.misralmahaba.example").replace(/\/$/, "");
const withUrl = (txt) => txt.replaceAll("https://www.misralmahaba.example", SITE_URL);
const r = (p) => readFileSync(u(p), "utf8");
const css = ["tokens", "base", "components", "sections"].map((f) => r(`src/styles/${f}.css`)).join("\n").replace(/\/\*[\s\S]*?\*\//g, "").replace(/\n\s*\n/g, "\n");
const camel = (f) => f.replace(/\.\w+$/, "").replace(/-(\w)/g, (_, c) => c.toUpperCase());
const img = Object.fromEntries(readdirSync(u("src/assets/img/")).map((f) => [camel(f), "data:image/webp;base64," + readFileSync(u("src/assets/img/" + f)).toString("base64")]));
const imgJs = "/* generated by build.mjs from src/assets/img */\nconst IMG = " + JSON.stringify(img) + ";";
const js = withUrl([imgJs, ...["src/utils/i18n.js", "src/data/site.js", "src/data/departments.js", "src/data/services.js", "src/data/doctors.js", "src/data/content.js",
  "src/services/api.js", "src/utils/core.js", "src/components/ui.js",
  "src/pages/home.js", "src/pages/catalog.js", "src/pages/people.js", "src/pages/booking.js", "src/main.js"].map(r)].join("\n;\n"));
const head = `<title>مستشفى مصر المحبة</title>
<meta name="description" content="مستشفى مصر المحبة ببني مزار – المنيا. صحتكم مسئوليتنا… ورعايتكم مهمتنا.">
<meta name="theme-color" content="#0F6CB4">
<link rel="icon" href="${img.logo96}">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;500;600&family=Readex+Pro:wght@500;600&display=swap">
<style>${css}</style>`;
const body = `<div id="app"><noscript><p style="padding:2rem">يرجى تفعيل JavaScript، أو الاتصال على 086 384 0801.</p></noscript></div>\n<script>${js}</script>`;
mkdirSync(u("dist/"), { recursive: true });
writeFileSync(u("dist/index.html"), `<!doctype html>\n<html lang="ar" dir="rtl">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n${head}\n</head>\n<body>\n${body}\n</body>\n</html>\n`);
if (process.env.ARTIFACT) writeFileSync(u("dist/artifact.html"), `${head}\n${body}\n`);
for (const f of ["robots.txt", "sitemap.xml"]) writeFileSync(u(`dist/${f}`), withUrl(r(`public/${f}`)));
console.log("built", (r("dist/index.html").length / 1024).toFixed(1) + "KB");
